name: 🧠 Brain Dump
description: Quick idea or thought - figure out the details later
title: "[Brain Dump]: "
labels: ["💡 idea"]
body:
  - type: markdown
    attributes:
      value: |
        🧠 **Quick Capture Mode** - Just get the thought out of your head!
        
        Fill in what you know now, skip everything else. You can always add more details later.

  - type: textarea
    id: idea
    attributes:
      label: What's the idea?
      description: Just write down the thought before you forget it!
      placeholder: Quick brain dump here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (Optional)
      description: Any quick context that might help later?
      placeholder: Where did this idea come from? Why now?
    validations:
      required: false

  - type: input
    id: tool
    attributes:
      label: Related Tool (Optional)
      description: Is this related to a specific part of the checklist?
      placeholder: e.g., Boundaries, Planner, Contract, etc.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Random Notes (Optional)
      description: Anything else swimming around in your brain?
      placeholder: Additional thoughts, half-baked ideas, connections...
    validations:
      required: false
