name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["✨ enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Explain the need for this feature...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives you've considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this feature?
      options:
        - "P: Idea"
        - "P: Do Later"
        - "P: Do Soon"
        - "P: Do Now"
      default: 0
    validations:
      required: false

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of this issue
      options:
        - "S: Brain Dump"
        - "S: Active Work"
        - "S: Backlog"
        - "S: Done"
      default: 0
    validations:
      required: false

  - type: dropdown
    id: milestone
    attributes:
      label: Milestone
      description: Which version should this feature be included in?
      options:
        - "V: 6.0"
        - "V: 7.0"
        - "V: 8.0"
        - "Backlog"
      default: 3
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
    validations:
      required: false
