name: 📖 User Story
description: Define a user story for development
title: "[Story]: "
labels: ["📖 user-story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a user story! Please fill out the details below.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: As a [type of user], I want [goal] so that [benefit]
      placeholder: |
        As a [type of user]
        I want [goal]
        So that [benefit]
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional background or context for this story
      placeholder: Provide any relevant context...
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this story to be complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation notes
      placeholder: Technical details, dependencies, constraints...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this story?
      options:
        - "P: Do Soon"
        - "P: Do Later"
        - "P: Idea"
      default: 0
    validations:
      required: false

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of this issue
      options:
        - "S: Brain Dump"
        - "S: Active Work"
        - "S: Backlog"
        - "S: Done"
      default: 0
    validations:
      required: false

  - type: dropdown
    id: milestone
    attributes:
      label: Milestone
      description: Which version should this story be included in?
      options:
        - "V: 6.0"
        - "V: 7.0"
        - "V: 8.0"
        - "Backlog"
      default: 3
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or related issues
    validations:
      required: false
